### ISSUE TITLE
Copy to clipboard not working on Firefox

### ISSUE THREAD

**Issue by rfoel** [Ghosh/uiGradients#174]
I tried to use the option to copy to clipboard on Firefox and it didn't work, then tried again on Chrome and it worked. It may be my browser or an issue with the Firefox.

**Comment by schmanat** [comment]
I can repoduce this bug. I'm using Windows 10 Enterprise 64 bit (version: 1607 systembuild: 14393.105) with the latest firefox 48.0.2.

I try other browsers like IE 11 and Edge, latest version of chrome without any problems.

It seems that firefox couldn't trigger the copy function.
If I copy a gradient on the other browsers i will see an "success" message "You got it. Go make something awesome!" on Firefox this messag will never show.

Same issue if I try to copy only one color code (shown on the top, left side).

**Comment by rfoel** [comment]
@schmanat That's right. I was using Firefox on a Linux dist and now I'm using Firefox on Windows 10 and it still happens.

**Comment by rfoel** [comment]
Seems to be a issue with the ZeroClipboard on Firefox.

https://github.com/zeroclipboard/zeroclipboard/issues/598

**Comment by rfoel** [comment]
I think I got it, it's the Flash Player. I installed it and now it works with a small bug though. The success message doesn't display right after clicking to copy.

ZeroClipboard uses Flash, you can check the demo on:
http://zeroclipboard.org/

**Comment by rfoel** [comment]
A better approach would be using [clipboard.js](https://clipboardjs.com/), which does not require Flash.

**Comment by schmanat** [comment]
OK thans for your search. I hate Flash: :smile:

**Comment by Ghosh** [comment]
Thanks for reporting this. I actually had contemplated using clipboard.js over zeroclipboard. The problem with clipboard.js is that it doesn't work on safari. 

The number of users accessing the site on safari vs. firefox is roughly the same. Ergo, it's a small tradeoff to use zeroclipboard and be able to provide the copy functionality to all.

Since the issue has already been reported on zeroclipboard, I am going to go ahead and close this issue now.
