### ISSUE TITLE
[Feature Request] Image creation

### ISSUE THREAD

**Issue by christopherburton** [ghosh/uiGradients#220]
Would be awesome if your project could render a HQ image with a click of a button for desktop wallpapers.

**Comment by ghosh** [comment]
Hi @christopherburton, thanks for bringing this up.

I am working on a v2.0 of uigradients and this is definitely something which is in the works. You can take a sneak peak at the code here - https://github.com/ghosh/uiGradients/blob/2.0/src/services/gradientDownloader.js

Since you brought this up, a quick question to you - What do you think the size of the image should be?

The way I see it, there are two options:-
- A fixed size based on the most popular browser size
- A dynamic size based on the current users display resolution

Just something I have been thinking about, yet to take a final call.

**Comment by christopherburton** [comment]
Hey, @ghosh. Glad you already thought of this. This is a good question. If I were doing it, I would go based on the user's display resolution if we're talking about desktop wallpapers.

**Comment by ghosh** [comment]
Released in 2.0
